
function show1(){
document.getElementById("x1").style.visibility="visible";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show2(){
document.getElementById("x2").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show3(){
document.getElementById("x3").style.visibility="visible";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show4(){
document.getElementById("x4").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show5(){
document.getElementById("x5").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show6(){
document.getElementById("x6").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show7(){
document.getElementById("x7").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show8(){
document.getElementById("x8").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show9(){
document.getElementById("x9").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show10(){
document.getElementById("x10").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x11").style.visibility="hidden";
}
function show11(){
document.getElementById("x10").style.visibility="visible";
document.getElementById("x1").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
}

function abc(){
document.getElementById("x11").style.visibility="hidden";
document.getElementById("x10").style.visibility="hidden";
document.getElementById("x9").style.visibility="hidden";
document.getElementById("x8").style.visibility="hidden";
document.getElementById("x7").style.visibility="hidden";
document.getElementById("x6").style.visibility="hidden";
document.getElementById("x5").style.visibility="hidden";
document.getElementById("x4").style.visibility="hidden";
document.getElementById("x3").style.visibility="hidden";
document.getElementById("x2").style.visibility="hidden";
document.getElementById("x1").style.visibility="hidden";
}